ref: update circleci orb v 3
cypress-io/cypress-realworld-testing pull request #260
Opened 2023-02-28 19:07 UTC by jordanpowell88

This PR updates CI to use the Cypress CircleCI Orb  `v3`.

2023-02-28 21:24 UTC, jaffrepaul requested changes
I think keeping the name param on each run is useful and even keeping the comments above them help grok this here and in Circle.

2023-02-28 21:27 UTC, jennifer-shehane requested changes
Yes, I was about to say the same as Paul. Since the Name has been removed, this would break any status checks setup in GitHub essentially if there are any. We shouldn't be changing the name of jobs.

Previously:

<img width="697" alt="Screen Shot 2023-02-28 at 4 25 59 PM" src="https://user-images.githubusercontent.com/1271364/221984031-32082a91-2798-4870-bbe3-91c88199d79c.png">

Now:

<img width="679" alt="Screen Shot 2023-02-28 at 4 26 18 PM" src="https://user-images.githubusercontent.com/1271364/221984054-609e518a-3214-4361-b665-a75744ac8479.png">

2023-03-01 18:06 UTC, jaffrepaul approved these changes

2023-03-01 20:28 UTC, jordanpowell88 commented
> 

This is resolved now @jennifer-shehane going to merge

2023-03-01 20:28 UTC, merged